name: manual-deploy-nonprod
on:
  workflow_dispatch:
    inputs:
      deployment_name:
        description: 'Deployment name'
        required: true
        type: choice
        options:
          - 'sli-dev-usea1'
          - 'sli-qa-usea1'


jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    with:
      deployment_name: ${{ github.event.inputs.deployment_name }}
      push_artifacts: "true"
    secrets: inherit

  cd:
    uses: ./.github/workflows/cd.yaml
    needs: ci
    with:
      deployment_name: ${{ github.event.inputs.deployment_name }}
    secrets: inherit
