name: on-push-main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    with:
      deployment_name: "sli-qa-usea1"
    secrets: inherit

  cd:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/cd.yaml
    needs: ci
    with:
      deployment_name: "sli-qa-usea1"
    secrets: inherit
